version: "3.8"

services:
    nginx:
        image: nginx:alpine
        container_name: payment-gateway-nginx
        ports:
            - "9999:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api-1
            - api-2
        networks:
            - internal
        deploy:
            resources:
                limits:
                    cpus: "0.1"
                    memory: "20MB"
        restart: unless-stopped

    redis:
        image: redis:7-alpine
        container_name: payment-gateway-redis
        command: redis-server --maxmemory 80mb --maxmemory-policy allkeys-lru --save ""
        networks:
            - internal
        deploy:
            resources:
                limits:
                    cpus: "0.2"
                    memory: "90MB"
        restart: unless-stopped

    api-1:
        image: your-dockerhub-username/payment-gateway:latest
        container_name: payment-gateway-api-1
        environment:
            - PORT=8080
            - REDIS_URL=redis:6379
            - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
            - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
            - INSTANCE_ID=api-1
        networks:
            - internal
            - payment-processor
        depends_on:
            - redis
        deploy:
            resources:
                limits:
                    cpus: "0.6"
                    memory: "120MB"
        restart: unless-stopped

    api-2:
        image: your-dockerhub-username/payment-gateway:latest
        container_name: payment-gateway-api-2
        environment:
            - PORT=8080
            - REDIS_URL=redis:6379
            - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
            - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
            - INSTANCE_ID=api-2
        networks:
            - internal
            - payment-processor
        depends_on:
            - redis
        deploy:
            resources:
                limits:
                    cpus: "0.6"
                    memory: "120MB"
        restart: unless-stopped

networks:
    payment-processor:
        external: true
    internal:
        driver: bridge
